# Generated by Django 4.2.10 on 2024-02-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esl',
            old_name='isim',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='esl',
            old_name='soyisim',
            new_name='username2',
        ),
    ]
