# Generated by Django 4.2.10 on 2024-02-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='esl',
        ),
    ]
