# Generated by Django 4.2.10 on 2024-02-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_delete_esl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
