# Generated by Django 4.2.10 on 2024-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('smptserver', models.CharField(max_length=30)),
                ('smptpassword', models.CharField(max_length=30)),
                ('smptemail', models.CharField(max_length=30)),
                ('smptpport', models.CharField(blank=True, max_length=30)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('instgaram', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=30)),
                ('aboutus', models.CharField(blank=True, max_length=30)),
                ('references', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=30)),
            ],
        ),
    ]
