# Generated by Django 4.2.10 on 2024-02-21 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smptemail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smptpport',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smptserver',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
