# Generated by Django 4.2.10 on 2024-02-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='acount',
            new_name='amount',
        ),
    ]
