# Generated by Django 4.2.10 on 2024-02-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='images',
            name='keywords',
        ),
    ]
