# Generated by Django 4.2.10 on 2024-02-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_images_descriptions_remove_images_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
