# Generated by Django 4.2.10 on 2024-02-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_image_category_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
