# Generated by Django 4.2.10 on 2024-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın'), ('çocuk', 'Çocuk')], max_length=10),
        ),
    ]
