# Generated by Django 4.2.10 on 2024-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_at',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
